name: p5_fusion_app
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  p5_fusion_dart: ^1.0.5
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.15

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: assets/controller.png

flutter_native_splash:
  color: "#17222b"

flutter_app_name:
  name: "Persona 5 Fusion Calculator"
